/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author alunos
 */
public class menu_GUI extends javax.swing.JFrame {
        private model.funcoes_DAO dao;


    /**
     * Creates new form menu_GUI
     */
    public menu_GUI() {
        
      initComponents();

        // Passa a própria tela (this) para a instância do DAO
        this.dao = new model.funcoes_DAO(this);
        configurarBotoesComImagem();

        // Configuração do modelo da tabela de ativos
        javax.swing.table.DefaultTableModel modeloCarrinho = new javax.swing.table.DefaultTableModel(
            new Object[][] {}, 
            new String[] {"Item", "Preço", "Kcal"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabela_ativos.setModel(modeloCarrinho);
    }

    // ==========================================
    // GETTERS PARA O DAO ACESSAR OS COMPONENTES
    // ==========================================
    public javax.swing.JTable getTabelaAtivos() {
        return tabela_ativos;
    }

    public javax.swing.JLabel getValtotTxt() {
        return valtot_txt;
    }

    public javax.swing.JLabel getTotalkcalTxt() {
        return totalkcal_txt;
    }
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tela = new javax.swing.JTabbedPane();
        tprincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabela_ativos = new javax.swing.JTable();
        valtot_txt = new javax.swing.JLabel();
        rem_BTN = new javax.swing.JButton();
        fina_BTN = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn_xchicken = new javax.swing.JButton();
        btn_xfish = new javax.swing.JButton();
        btn_xovo = new javax.swing.JButton();
        btn_xtudo = new javax.swing.JButton();
        btn_xsalada4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_onion = new javax.swing.JButton();
        btn_nuggets = new javax.swing.JButton();
        btn_batata = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_refri = new javax.swing.JButton();
        btn_suco = new javax.swing.JButton();
        btn_agua = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_combo_gui = new javax.swing.JButton();
        btn_combo_slark = new javax.swing.JButton();
        btn_combo_chinabet = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_sorvete = new javax.swing.JButton();
        btn_brownie = new javax.swing.JButton();
        btn_cookie = new javax.swing.JButton();
        totalkcal_txt = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tela.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                telaStateChanged(evt);
            }
        });

        tprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("Lanches  Ceap");
        tprincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        tabela_ativos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Preço", "Kcal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabela_ativos);

        tprincipal.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 230, 120));

        valtot_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        valtot_txt.setText("TOTAL: 0.0");
        tprincipal.add(valtot_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        rem_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        rem_BTN.setText("Remover item");
        rem_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rem_BTNActionPerformed(evt);
            }
        });
        tprincipal.add(rem_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, -1));

        fina_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        fina_BTN.setText("FINALIZAR PEDIDO");
        fina_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fina_BTNActionPerformed(evt);
            }
        });
        tprincipal.add(fina_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 670, -1, -1));

        jPanel2.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btn_xchicken.setText("X-Chicken (Preço: R$ 23,00 | 540 kcal)");
        btn_xchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xchickenActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xchicken);

        btn_xfish.setText("X-Fish (Preço: R$ 24,00 | 480 kcal)");
        btn_xfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xfishActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xfish);

        btn_xovo.setText("X-Ovo (Preço: R$ 22,00 | 610 kcal)");
        btn_xovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xovoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xovo);

        btn_xtudo.setText("X-Tudo (Preço: R$ 28,00 | 850 kcal)");
        btn_xtudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xtudoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xtudo);

        btn_xsalada4.setText("X-Salada (Preço: R$ 20,00 | 520 kcal)");
        btn_xsalada4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xsalada4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_xsalada4);

        jTabbedPane1.addTab("Lanches", jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btn_onion.setText("Onion Rings (Preço: R$ 12,00 | 380 kcal)");
        btn_onion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_onionActionPerformed(evt);
            }
        });
        jPanel3.add(btn_onion);

        btn_nuggets.setText("Nuggets (Preço: R$ 14,00 | 410 kcal)");
        btn_nuggets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuggetsActionPerformed(evt);
            }
        });
        jPanel3.add(btn_nuggets);

        btn_batata.setText("Batata (Preço: R$ 10,00 | 350 kcal)");
        btn_batata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batataActionPerformed(evt);
            }
        });
        jPanel3.add(btn_batata);

        jTabbedPane1.addTab("acompanhamentos", jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btn_refri.setText("Refrigerante (Preço: R$ 7,00 | 150 kcal)");
        btn_refri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refriActionPerformed(evt);
            }
        });
        jPanel4.add(btn_refri);

        btn_suco.setText(" Suco (Preço: R$ 8,50 | 120 kcal)");
        btn_suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sucoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_suco);

        btn_agua.setText("Água (Preço: R$ 4,00 | 0 kcal)");
        btn_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aguaActionPerformed(evt);
            }
        });
        jPanel4.add(btn_agua);

        jTabbedPane1.addTab("Bedidas", jPanel4);

        jPanel6.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btn_combo_gui.setText("<html><center><b>Combo do Gui</b><br><font size='2'>Cookie + X-Ovo + Suco</font><br><font color='green'><b>R$ 34,00</b></font> | 1010 kcal</center></html>\n");
        btn_combo_gui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combo_guiActionPerformed(evt);
            }
        });
        jPanel6.add(btn_combo_gui);

        btn_combo_slark.setText("<html><center><b>Combão Slark</b><br>Refri + X-Tudo + Sorvete<br><b>R$ 37,00</b> | 1220 kcal</center></html>");
        btn_combo_slark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combo_slarkActionPerformed(evt);
            }
        });
        jPanel6.add(btn_combo_slark);

        btn_combo_chinabet.setText("<html><center><b>Combão Chinabet</b><br>X-Fish + Brownie + Água<br><b>R$ 33,00</b> | 820 kcal</center></html>\n");
        btn_combo_chinabet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_combo_chinabetActionPerformed(evt);
            }
        });
        jPanel6.add(btn_combo_chinabet);

        jTabbedPane1.addTab("Combos", jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        btn_sorvete.setText("Sorvete (Preço: R$ 6,00 | 220 kcal)");
        btn_sorvete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sorveteActionPerformed(evt);
            }
        });
        jPanel7.add(btn_sorvete);

        btn_brownie.setText("Brownie (Preço: R$ 9,00 | 340 kcal)");
        btn_brownie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brownieActionPerformed(evt);
            }
        });
        jPanel7.add(btn_brownie);

        btn_cookie.setText("Cookie do Gui (Preço: R$ 8,00 | 280 kcal)");
        btn_cookie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cookieActionPerformed(evt);
            }
        });
        jPanel7.add(btn_cookie);

        jTabbedPane1.addTab("sobremessas", jPanel7);

        tprincipal.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 580, 690));

        totalkcal_txt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        totalkcal_txt.setText("Kcals Totais: 0 Kcal");
        tprincipal.add(totalkcal_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, -1, -1));

        tela.addTab("Principal", tprincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(840, 981));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void telaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_telaStateChanged

    }//GEN-LAST:event_telaStateChanged

    private void btn_refriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refriActionPerformed
dao.adicionarItem("Refrigerante", 7.00, 150);       // TODO add your handling code here:
    }//GEN-LAST:event_btn_refriActionPerformed

    private void btn_xsalada4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xsalada4ActionPerformed
dao.adicionarItem("X-Salada", 20.00, 520);  // TODO add your handling code here:
    }//GEN-LAST:event_btn_xsalada4ActionPerformed

    private void btn_xtudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xtudoActionPerformed
dao.adicionarItem("X-Tudo", 28.00, 850);
    // TODO add your handling code here:
    }//GEN-LAST:event_btn_xtudoActionPerformed

    private void btn_xovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xovoActionPerformed
dao.adicionarItem("X-Ovo", 22.00, 610);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_xovoActionPerformed

    private void btn_xfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xfishActionPerformed
dao.adicionarItem("X-Fish", 24.00, 480);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xfishActionPerformed

    private void btn_xchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xchickenActionPerformed
dao.adicionarItem("X-Chicken", 23.00, 540);;        // TODO add your handling code here:
    }//GEN-LAST:event_btn_xchickenActionPerformed

    private void btn_onionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_onionActionPerformed
dao.adicionarItem("Onion Rings", 12.00, 380);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_onionActionPerformed

    private void btn_nuggetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuggetsActionPerformed
dao.adicionarItem("Nuggets", 14.00, 410);     // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuggetsActionPerformed

    private void btn_batataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batataActionPerformed
dao.adicionarItem("Batata", 10.00, 350);      // TODO add your handling code here:
    }//GEN-LAST:event_btn_batataActionPerformed

    private void btn_sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sucoActionPerformed
dao.adicionarItem("Suco", 8.50, 120);   // TODO add your handling code here:
    }//GEN-LAST:event_btn_sucoActionPerformed

    private void btn_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aguaActionPerformed
    dao.adicionarItem("Água", 4.00, 0);// TODO add your handling code here:
    }//GEN-LAST:event_btn_aguaActionPerformed

    private void btn_sorveteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sorveteActionPerformed
dao.adicionarItem("Sorvete", 6.00, 220);      // TODO add your handling code here:
    }//GEN-LAST:event_btn_sorveteActionPerformed

    private void btn_brownieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brownieActionPerformed
dao.adicionarItem("Brownie", 9.00, 340);       // TODO add your handling code here:
    }//GEN-LAST:event_btn_brownieActionPerformed

    private void btn_cookieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cookieActionPerformed
dao.adicionarItem("Cookie do Gui", 8.00, 280);      // TODO add your handling code here:
    }//GEN-LAST:event_btn_cookieActionPerformed

    private void btn_combo_guiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combo_guiActionPerformed
dao.adicionarItem("Combo do Gui", 34.00, 1010);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_combo_guiActionPerformed

    private void btn_combo_slarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combo_slarkActionPerformed
dao.adicionarItem("Combão Slark", 37.00, 1220);       // TODO add your handling code here:
    }//GEN-LAST:event_btn_combo_slarkActionPerformed

    private void btn_combo_chinabetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_combo_chinabetActionPerformed
dao.adicionarItem("Combão Chinabet", 33.00, 820);    // TODO add your handling code here:
    }//GEN-LAST:event_btn_combo_chinabetActionPerformed

    private void rem_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rem_BTNActionPerformed
dao.removerItemSelecionado();// TODO add your handling code here:
    }//GEN-LAST:event_rem_BTNActionPerformed

    private void fina_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fina_BTNActionPerformed
dao.finalizarPedido();   // TODO add your handling code here:
    }//GEN-LAST:event_fina_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agua;
    private javax.swing.JButton btn_batata;
    private javax.swing.JButton btn_brownie;
    private javax.swing.JButton btn_combo_chinabet;
    private javax.swing.JButton btn_combo_gui;
    private javax.swing.JButton btn_combo_slark;
    private javax.swing.JButton btn_cookie;
    private javax.swing.JButton btn_nuggets;
    private javax.swing.JButton btn_onion;
    private javax.swing.JButton btn_refri;
    private javax.swing.JButton btn_sorvete;
    private javax.swing.JButton btn_suco;
    private javax.swing.JButton btn_xchicken;
    private javax.swing.JButton btn_xfish;
    private javax.swing.JButton btn_xovo;
    private javax.swing.JButton btn_xsalada4;
    private javax.swing.JButton btn_xtudo;
    private javax.swing.JButton fina_BTN;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton rem_BTN;
    public static javax.swing.JTable tabela_ativos;
    public static javax.swing.JTabbedPane tela;
    private javax.swing.JLabel totalkcal_txt;
    private javax.swing.JPanel tprincipal;
    private javax.swing.JLabel valtot_txt;
    // End of variables declaration//GEN-END:variables
public static void main(String args[]) {
        /* Define o visual Nimbus */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(menu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Cria e exibe a tela */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_GUI().setVisible(true);
            }
        });
    }
// ==========================================
    // MÉTODOS PARA CARREGAR AS IMAGENS DO TOTEM
    // ==========================================
private javax.swing.ImageIcon carregarIcone(String nomeImagem) {
    try {
        // 1. Tenta carregar pelo classpath da aplicação
        java.net.URL imgURL = menu_GUI.class.getResource("/image/" + nomeImagem);
        if (imgURL != null) {
            javax.swing.ImageIcon iconOriginal = new javax.swing.ImageIcon(imgURL);
            java.awt.Image imgRedimensionada = iconOriginal.getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            return new javax.swing.ImageIcon(imgRedimensionada);
        }

        // 2. Fallback: procura diretamente na pasta do projeto no disco
        String caminhoFisico = "src/image/" + nomeImagem;
        java.io.File arquivo = new java.io.File(caminhoFisico);
        
        if (arquivo.exists()) {
            javax.swing.ImageIcon iconOriginal = new javax.swing.ImageIcon(arquivo.getAbsolutePath());
            java.awt.Image imgRedimensionada = iconOriginal.getImage().getScaledInstance(100, 100, java.awt.Image.SCALE_SMOOTH);
            return new javax.swing.ImageIcon(imgRedimensionada);
        } else {
            System.err.println("Imagem não encontrada nem no classpath nem no disco: " + nomeImagem);
            return null;
        }
    } catch (Exception e) {
        System.err.println("Erro ao carregar imagem " + nomeImagem + ": " + e.getMessage());
        return null;
    }
}

    private void configurarBotoesComImagem() {
        java.util.function.BiConsumer<javax.swing.JButton, String> aplicarIcone = (btn, nomeFoto) -> {
            if (btn != null) {
                btn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btn.setIcon(carregarIcone(nomeFoto));
            }
        };

        // LANCHES
        aplicarIcone.accept(btn_xsalada4, "xcal.jpg");
        btn_xsalada4.setText("<html><center><b>X-Salada</b><br><font color='green'>R$ 20,00</font><br><font size='2' color='gray'>520 kcal</font></center></html>");

        aplicarIcone.accept(btn_xtudo, "xcal.jpg");
        btn_xtudo.setText("<html><center><b>X-Tudo</b><br><font color='green'>R$ 28,00</font><br><font size='2' color='gray'>850 kcal</font></center></html>");

        aplicarIcone.accept(btn_xovo, "xegg.jpg");
        btn_xovo.setText("<html><center><b>X-Ovo</b><br><font color='green'>R$ 22,00</font><br><font size='2' color='gray'>610 kcal</font></center></html>");

        aplicarIcone.accept(btn_xfish, "xfish.jpg");
        btn_xfish.setText("<html><center><b>X-Fish</b><br><font color='green'>R$ 24,00</font><br><font size='2' color='gray'>480 kcal</font></center></html>");

        aplicarIcone.accept(btn_xchicken, "xfrango.jpg");
        btn_xchicken.setText("<html><center><b>X-Chicken</b><br><font color='green'>R$ 23,00</font><br><font size='2' color='gray'>540 kcal</font></center></html>");

        // ACOMPANHAMENTOS
        aplicarIcone.accept(btn_onion, "ring.jpg");
        btn_onion.setText("<html><center><b>Onion Rings</b><br><font color='green'>R$ 12,00</font><br><font size='2' color='gray'>380 kcal</font></center></html>");

        aplicarIcone.accept(btn_nuggets, "nug.jpg");
        btn_nuggets.setText("<html><center><b>Nuggets</b><br><font color='green'>R$ 14,00</font><br><font size='2' color='gray'>410 kcal</font></center></html>");

        aplicarIcone.accept(btn_batata, "frit.jpg");
        btn_batata.setText("<html><center><b>Batata Frita</b><br><font color='green'>R$ 10,00</font><br><font size='2' color='gray'>350 kcal</font></center></html>");

        // BEBIDAS
        aplicarIcone.accept(btn_refri, "coc.jpg");
        btn_refri.setText("<html><center><b>Refrigerante</b><br><font color='green'>R$ 7,00</font><br><font size='2' color='gray'>150 kcal</font></center></html>");

        aplicarIcone.accept(btn_suco, "suc.jpg");
        btn_suco.setText("<html><center><b>Suco</b><br><font color='green'>R$ 8,50</font><br><font size='2' color='gray'>120 kcal</font></center></html>");

        aplicarIcone.accept(btn_agua, "agua.jpg");
        btn_agua.setText("<html><center><b>Água</b><br><font color='green'>R$ 4,00</font><br><font size='2' color='gray'>0 kcal</font></center></html>");

        // SOBREMESAS
        aplicarIcone.accept(btn_sorvete, "sor.jpg");
        btn_sorvete.setText("<html><center><b>Sorvete</b><br><font color='green'>R$ 6,00</font><br><font size='2' color='gray'>220 kcal</font></center></html>");

        aplicarIcone.accept(btn_brownie, "brow.jpg");
        btn_brownie.setText("<html><center><b>Brownie</b><br><font color='green'>R$ 9,00</font><br><font size='2' color='gray'>340 kcal</font></center></html>");

        aplicarIcone.accept(btn_cookie, "cook.jpg");
        btn_cookie.setText("<html><center><b>Cookie do Gui</b><br><font color='green'>R$ 8,00</font><br><font size='2' color='gray'>280 kcal</font></center></html>");
        
        // Combo do Gui
aplicarIcone.accept(btn_combo_gui, "Captura de tela 2026-09-21 193415.png");
btn_combo_gui.setText("<html><center><b>Combo do Gui</b><br>"
        + "<font size='2' color='gray'>Cookie + X-Ovo + Suco</font><br>"
        + "<font color='green'><b>R$ 34,00</b></font> | 1010 kcal</center></html>");

// Combão Slark
aplicarIcone.accept(btn_combo_slark, "Captura de tela 2026-09-21 193403.png");
btn_combo_slark.setText("<html><center><b>Combão Slark</b><br>"
        + "<font size='2' color='gray'>Refri + X-Tudo + Sorvete</font><br>"
        + "<font color='green'><b>R$ 37,00</b></font> | 1220 kcal</center></html>");

// Combão Chinabet
aplicarIcone.accept(btn_combo_chinabet, "Captura de tela 2026-09-21 193345.png");
btn_combo_chinabet.setText("<html><center><b>Combão Chinabet</b><br>"
        + "<font size='2' color='gray'>X-Fish + Brownie + Água</font><br>"
        + "<font color='green'><b>R$ 33,00</b></font> | 820 kcal</center></html>");
    }


}
